#!/bin/bash
set -eu
shopt -s expand_aliases
source ./common

CN_DOMAIN=$1

godaddy_dns_put_record(){
  curl -s -X PUT "${GODADDY_API_URL}/v1/domains/${DOMAIN}/records/${DNS_REC_TYPE}" \
    -H  "accept: application/json" -H  "Content-Type: application/json" \
    -H  "Authorization: sso-key ${GODADDY_API_KEY}:${GODADDY_API_SECRET}" \
    -d "[{ \"data\": \"${DNS_REC_DATA}\", \"name\": \"${DNS_REC_NAME}\", \"ttl\": ${DNS_REC_TTL} }]"
}


test_godaddy_record_exists(){
while true; do
  sleep 3
  # r=$(dig +short txt ${DNS_REC_NAME}.${DOMAIN} @8.8.8.8)
  r=$(dig +short txt ${DNS_REC_NAME}.${DOMAIN})
  [ -z "$r" ] || break
  # check if wildcard i.e. *.example.org
  r=$(dig +short txt _acme-challenge.${DOMAIN})
  [ -z "$r" ] || break
done
}


windows_dns_add_record(){
  cmd="Add-DnsServerResourceRecord -ZoneName $DOMAIN -Name  "${DNS_REC_NAME}" -Txt -DescriptiveText \"${DNS_REC_DATA}\""
  run_cmd $WINDOWS_DNS_HOST "$cmd" winrm 5986
}


main(){
  set_acme_dns_challenge_vars $CN_DOMAIN
  godaddy_dns_put_record
  test_godaddy_record_exists
}


main
