#!/usr/bin/env bash
set -eu
shopt -s expand_aliases
source ./common


godaddy(){
  curl -X PUT "${GODADDY_API_URL}/v1/domains/${DOMAIN}/records/${DNS_REC_TYPE}" \
  -H  "accept: application/json" -H  "Content-Type: application/json" -H  \
  "Authorization: sso-key ${GODADDY_API_KEY}:${GODADDY_API_SECRET}" \
  -d "[{ \"data\": \"${DNS_REC_DATA}\", \"name\": \"${DNS_REC_NAME}\", \"ttl\": ${DNS_REC_TTL} }]"
}


windows_dns(){
  echo "Cleanup"
  cmd="Remove-DnsServerResourceRecord -ZoneName $DOMAIN -RRType Txt -Name ${DNS_REC_NAME} -force"
  run_cmd $WINDOWS_DNS_HOST "$cmd" winrm 5986
}


main(){
  get_acme_dns_challenge_vars
  windows_dns
}


main
